# Configuración de Base de Datos (Credenciales fijas para desarrollo)
spring.datasource.url=${REPARASUITE_DB_URL:jdbc:postgresql://localhost:5432/reparasuite}
spring.datasource.username=${REPARASUITE_DB_USERNAME:postgres}
spring.datasource.password=123456

# Validación de Tablas
spring.jpa.hibernate.ddl-auto=validate

# Seguridad y Red (CORS para tu Frontend en Angular/React)
reparasuite.proxy.trust-forward-headers=false
reparasuite.cors.allowed-origin-patterns=http://localhost:4200,http://127.0.0.1:4200,http://localhost:4300,http://127.0.0.1:4300

# Swagger (Documentación visual de la API activa)
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# --- MONITOREO Y SALUD (ACTUATOR) ---
# 1. Exponer los puntos de salud
management.endpoints.web.exposure.include=health,liveness,readiness
# 2. Mostrar todos los detalles (incluyendo si la DB está conectada)
management.endpoint.health.show-details=always