spring.datasource.url=jdbc:postgresql://localhost:5432/reparasuite
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update

reparasuite.jwt.secret=MI_CLAVE_SUPER_SECRETA_DE_64_CARACTERES_12345678901234567890123456
reparasuite.jwt.issuer=reparasuite-api
reparasuite.jwt.exp-min=30

reparasuite.proxy.trust-forward-headers=false
#reparasuite.cors.allowed-origin-patterns=http://localhost:4200,http://127.0.0.1:4200,http://localhost:4300,http://127.0.0.1:4300
reparasuite.cors.allowed-origin-patterns=http://localhost:4200,http://127.0.0.1:4200,http://localhost:4300,http://127.0.0.1:4300,http://192.168.1.10:4300
reparasuite.refresh-token.cookie-secure=false
reparasuite.refresh-token.cookie-same-site=Lax

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

management.endpoint.health.show-details=always

app.frontend-url=http://localhost:4300