server.port=8080

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

# Carga de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Carpeta uploads
reparasuite.upload-dir=uploads

# JWT
reparasuite.jwt.secret=MI_CLAVE_SUPER_SECRETA_DE_64_CARACTERES_12345678901234567890123456
reparasuite.jwt.issuer=reparasuite-api
reparasuite.jwt.exp-min=480

# CORS (se sobreescribe por perfil)
reparasuite.cors.allowed-origin-patterns=

# Swagger / OpenAPI (por defecto desactivado; activar por perfil)
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false