package com.reparasuite.api.model;

public enum EventoHistorialOt {
  OT_CREADA,
  CAMBIO_ESTADO,
  NOTA_AGREGADA,
  FOTO_SUBIDA,

  PRESUPUESTO_GUARDADO,
  PRESUPUESTO_ENVIADO,
  PRESUPUESTO_ACEPTADO,
  PRESUPUESTO_RECHAZADO,

  PAGO_MARCADO_TRANSFERENCIA,
  PAGO_COMPROBANTE_SUBIDO,
  CITA_RESERVADA,
  CITA_REPROGRAMADA,
  MENSAJE_ENVIADO
}
